package com.fromitt.stackoverflowtestapp.network

/*
 * @author Tkachov Vasyl
 * @since 14.10.2020
 */
object ArtistData {
    var artists = arrayOf(
        "Alejandra and Aeron",
        "Miguel Álvarez-Fernández",
        "Maryanne Amacher",
        "Charles Amirkhanian",
        "Christine Sun Kim",
        "Laurie Anderson",
        "Magali Babin",
        "William Basinski",
        "Pierre Bastien",
        "Harry Bertoia",
        "Jaap Blonk",
        "Baschet Brothers",
        "MW Burns",
        "Ken Butler",
        "Janet Cardiff",
        "Lawrence Chandler",
        "Richard Chartier",
        "Walton Creel",
        "Alvin Curran",
        "Lance Dann",
        "Tacita Dean",
        "Poulomi Desai",
        "Chantal Dumas",
        "Judy Dunaway",
        "Kyle Bobby Dunn",
        "Max Eastley",
        "eRikm",
        "Christian Fennesz",
        "Bill Fontana",
        "Terry Fox",
        "Bernhard Gal",
        "Reed Ghazala",
        "Kraig Grady",
        "Ken Gregory",
        "Steve Heimbecker",
        "Brenda Hutchinson",
        "Ryoji Ikeda",
        "Christopher Janney",
        "Miranda July",
        "GX Jupitter-Larsen",
        "Timo Kahlen",
        "Jacob Kirkegaard",
        "David Kristian",
        "Georg Klein",
        "Viacheslav Koleichuk",
        "Christina Kubisch",
        "Petri Kuljuntausta",
        "Yuri Landman",
        "Georges Lentz",
        "Augustine Leudar",
        "Arto Lindsay",
        "Francisco López",
        "Alvin Lucier",
        "Christian Marclay",
        "Miya Masaoka",
        "Stephan Mathieu",
        "Abinadi Meza",
        "Christof Migone",
        "George Bures Miller",
        "Haroon Mirza",
        "Moondog",
        "Gordon Monahan",
        "David Monacchi",
        "Meredith Monk",
        "Tracie Morris",
        "Charlotte Moorman",
        "Bruce Nauman",
        "Max Neuhaus",
        "Angel Nevarez & Valerie Tevere",
        "Carsten Nicolai",
        "Margaret Noble",
        "Mendi & Keith Obadike",
        "Yoko Ono",
        "Koka Nikoladze",
        "Charlemagne Palestine",
        "Paul Panhuysen",
        "Tristan Perich",
        "Norbert Walter Peters",
        "Liz Phillips",
        "Susan Philipsz",
        "Hans Reichel",
        "Boyd Rice",
        "Pipilotti Rist",
        "Manuel Rocha Iturbide",
        "Paul Rooney",
        "Rik Rue",
        "Janek Schaefer",
        "Stan Shaff",
        "Severed Heads",
        "Don Simmons",
        "Elliott Sharp",
        "George Smits",
        "Michael Snow",
        "Soundlab",
        "Rod Summers",
        "Takis",
        "Jeff Talman",
        "Robert Scott Thompson",
        "Gerda Nettesheim",
        "Jean Tinguely",
        "Yasunao Tone",
        "Trimpin",
        "Thomas Truax",
        "Edwin van der Heide",
        "David Van Tieghem",
        "Stephen Vitiello",
        "Carl Michael von Hausswolff",
        "Bill Viola",
        "Wolf Vostell",
        "Yoshi Wada",
        "Hildegard Westerkamp",
        "Daniel Wilson",
        "Mark Peter Wright",
        "LaMonte Young",
        "Pavel Zhagun",
        "Zimoun"
    )
}